x-syslog-logging: &syslog_logging
  driver: syslog
  options:
    syslog-address: udp://127.0.0.1:5514
    tag: "{{.Name}}"
    syslog-format: rfc5424micro

services:
  dbserver:
    image: mongo:8.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=minitwit
    volumes:
      - mongo_local_data:/data/db
    networks:
      - minitwit-network
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging: *syslog_logging

  webserver:
    image: antohay/webminitwitimage:latest
    volumes:
      - type: bind
        source: ${PWD}/new
        target: /app
      - type: bind
        source: ${PWD}/new/logs
        target: /usr/src/app/logs
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://dbserver:27017/minitwit
    networks:
      - minitwit-network
    logging: *syslog_logging
    deploy:
      replicas: 1
      # Rolling updates
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first

  central-rsyslog:
    image: antohay/central-rsyslog:latest
    environment:
      - RSYSLOG_RETENTION_DAYS=7
      - RSYSLOG_CLEANUP_INTERVAL_SECONDS=3600
    ports:
      - target: 514
        published: 5514
        protocol: tcp
        mode: host
      - target: 514
        published: 5514
        protocol: udp
        mode: host
    networks:
      - minitwit-network
    volumes:
      - rsyslog_data:/var/log/remote

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - minitwit-network
    volumes:
      - grafana_cloud_data:/var/lib/grafana
    logging: *syslog_logging

  prometheus:
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - minitwit-network
    logging: *syslog_logging

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - minitwit-network
    logging: *syslog_logging

  promtail:
    image: grafana/promtail:latest
    volumes:
      - type: volume
        source: rsyslog_data
        target: /var/log/remote
        read_only: true
      - type: bind
        source: ${PWD}/monitoring/promtail/config.yml
        target: /etc/promtail/config.yml
        read_only: true
    command: -config.file=/etc/promtail/config.yml
    networks:
      - minitwit-network
    logging: *syslog_logging

networks:
  minitwit-network:
    driver: overlay # Required for Swarm

volumes:
  prometheus_cloud_data:
    external: true
    name: minitwit_prometheus_cloud_data

  grafana_cloud_data:
    external: true
    name: minitwit_grafana_cloud_data

  rsyslog_data:
  webserver_logs:
  mongo_local_data: