# docker/web/Dockerfile.dev
FROM golang:1.25

WORKDIR /app

RUN curl -sSfL https://raw.githubusercontent.com/air-verse/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

# 2. Cache dependencies
COPY go.mod go.sum ./
RUN go mod download

COPY .air.toml ./

# 4. Run Air
CMD ["air", "-c", ".air.toml"]