name: Automated Release

#this autmoation is creating release uppon pushing changes to main branch
#To have proper number of version it is important to use correct labels in pull request

#naming: Version x.y.z
            #x - major
            #y - minor
            #z - patch
#Labels on pull request should be named as: bump:major', 'bump:minor', or 'bump:patch' to execute action properly
#If label will not be found, action will fail the test ! 

on:
  pull_request:
    branches:
      - main  # Trigger only when code is merged into main
    types: [closed]

permissions:
  contents: write  # Allows the robot to create tags and releases

jobs:
  build-and-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetches all history so it can find the previous version tag

      - name: Determine Version Bump
        id: bump_logic
        uses: zwaldowski/semver-release-action@v3
        with:
          # This looks for labels like 'bump:major', 'bump:minor', or 'bump:patch'
          # If no label is found, it defaults to a patch (0.0.X)
          bump: ${{ join(github.event.pull_request.labels.*.name, ',') }}
          github_token: ${{ secrets.RELEASE_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump_logic.outputs.version }}
          name: Release ${{ steps.bump_logic.outputs.version }}
          generate_release_notes: true  # Automatically writes the list of changes
        env:
          github_token: ${{ secrets.RELEASE_TOKEN }}